#!/usr/bin/env bash
# Wire MyTradingSpace into ~/.openclaw for phone dry-run (Telegram + skills).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OPENCLAW_DIR="${HOME}/.openclaw"
CONFIG="${OPENCLAW_DIR}/openclaw.json"
ENV_FILE="${OPENCLAW_DIR}/.env"
BACKUP="${OPENCLAW_DIR}/openclaw.json.bak.mytrading-$(date +%Y%m%d-%H%M%S)"

echo "MyTradingSpace phone dry-run setup"
echo "  repo: ${ROOT}"

mkdir -p "${OPENCLAW_DIR}"
cp -a "${CONFIG}" "${BACKUP}" 2>/dev/null || true
echo "  backup: ${BACKUP}"

# Polygon (+ optional Telegram) for exec / notify scripts
POLYGON=""
if [[ -f "${ROOT}/.env" ]]; then
  # shellcheck disable=SC1090
  set -a && source "${ROOT}/.env" && set +a
  POLYGON="${POLYGON_API_KEY:-}"
fi

{
  echo "# MyTradingSpace — generated by setup_phone_dryrun.sh"
  [[ -n "${POLYGON}" ]] && echo "POLYGON_API_KEY=${POLYGON}"
  [[ -n "${TELEGRAM_BOT_TOKEN:-}" ]] && echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}"
  [[ -n "${TELEGRAM_CHAT_ID:-}" ]] && echo "TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}"
  echo "MYTRADING_PYTHON=${ROOT}/.venv/bin/python"
} > "${ENV_FILE}"
chmod 600 "${ENV_FILE}"
echo "  wrote ${ENV_FILE}"

export ROOT
export TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"

"${ROOT}/.venv/bin/python" <<'PY'
import json
import os
from pathlib import Path

root = Path(os.environ["ROOT"])
config_path = Path.home() / ".openclaw" / "openclaw.json"
token = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()

with config_path.open(encoding="utf-8") as f:
    cfg = json.load(f)

agents = cfg.setdefault("agents", {})
defaults = agents.setdefault("defaults", {})
defaults["workspace"] = str(root / "openclaw" / "workspace")
defaults["repoRoot"] = str(root)
defaults["userTimezone"] = "America/New_York"
defaults["timeoutSeconds"] = 600
defaults["model"] = {"primary": "ollama/qwen3.6:latest"}
defaults.setdefault("models", {})["ollama/qwen3.6:latest"] = {}
skill_names = [
    "trading-orchestrator",
    "daily-unified-pilot",
    "fundamental-only",
    "phoenix-only",
]

lst = agents.setdefault("list", [])
found = False
for agent in lst:
    if agent.get("id") == "trading-orchestrator":
        agent["default"] = True
        agent.setdefault("identity", {})["name"] = "TradingOrchestrator"
        agent["skills"] = skill_names
        found = True
        break
if not found:
    lst.append(
        {
            "id": "trading-orchestrator",
            "default": True,
            "identity": {
                "name": "TradingOrchestrator",
                "theme": "Phoenix + Fundamental via MyTradingSpace",
                "emoji": "📈",
            },
            "skills": skill_names,
        }
    )

cfg.setdefault("env", {})["shellEnv"] = {"enabled": True}
tools = cfg.setdefault("tools", {})
tools["allow"] = list(dict.fromkeys(tools.get("allow", []) + ["exec", "read", "write", "message"]))
tools.setdefault("exec", {})["timeoutSec"] = 3600
cfg.setdefault("skills", {}).setdefault("load", {})["extraDirs"] = [
    str(root / "openclaw" / "workspace" / "skills")
]

gw = cfg.setdefault("gateway", {})
gw.setdefault("port", 18789)
gw.setdefault("bind", "loopback")
gw.setdefault("controlUi", {})["enabled"] = True

channels = cfg.setdefault("channels", {})
if token:
    channels["telegram"] = {
        "enabled": True,
        "botToken": token,
        "dmPolicy": "pairing",
        "groups": {"*": {"requireMention": True}},
    }
    print("  telegram: enabled (dmPolicy=pairing)")
else:
    print("  telegram: skipped — set TELEGRAM_BOT_TOKEN and re-run")

with config_path.open("w", encoding="utf-8") as f:
    json.dump(cfg, f, indent=2)
    f.write("\n")
print(f"  updated {config_path}")
PY

chmod +x "${SCRIPT_DIR}"/*.sh

echo ""
echo "--- openclaw doctor (skills) ---"
openclaw doctor 2>&1 | tail -20 || true

echo ""
echo "=== Next (phone dry-run) ==="
if [[ -z "${TELEGRAM_BOT_TOKEN:-}" ]]; then
  cat <<'EOF'

1) Telegram bot (2 min on phone):
   • Message @BotFather → /newbot → copy token
   • On Mac, re-run:
     TELEGRAM_BOT_TOKEN='123456:ABC...' ./openclaw/scripts/setup_phone_dryrun.sh

2) Restart gateway (Mac):
   openclaw gateway restart
   # or: kill existing gateway process and: openclaw gateway

3) On phone: open Telegram → your bot → send:
   Analyze AAPL as of 2026-05-15 with phoenix-fa

4) Approve first DM (Mac terminal):
   openclaw pairing list telegram
   openclaw pairing approve telegram <CODE>

EOF
else
  cat <<'EOF'

1) Restart gateway:  openclaw gateway restart
2) Phone → Telegram → your bot → message:
   Analyze AAPL as of 2026-05-15 with phoenix-fa
3) Mac: openclaw pairing list telegram
   openclaw pairing approve telegram <CODE>

EOF
fi

echo "Local smoke (no phone):"
echo "  cd ${ROOT} && openclaw agent --message 'Analyze AAPL as of 2026-05-15 phoenix-fa'"
